### PR TITLE
Replace anyref to externref. Improve numeric literals

### PR DESCRIPTION
**Pull request by MaxGraey**

### CODE REVIEW

**Comment by MaxGraey** [comment]
cc @syrusakbary @reklatsmasters

**Comment by reklatsmasters** [comment]
@MaxGraey Could you squash commits?

**Comment by MaxGraey** [comment]
Github support squashing in interface.

**Review by syrusakbary — APPROVED** [review]
Looks good!

**Comment by MaxGraey** [comment]
@syrusakbary Thanks! Could you also publish new release?

**Comment by MaxGraey** [comment]
> Thanks! Could you also publish new release?

up

**Pull request merged**
